# Generated by Django 4.1.3 on 2022-12-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorFirstName', models.CharField(max_length=500)),
                ('DoctorLastName', models.CharField(max_length=500)),
                ('DoctorEmail', models.CharField(max_length=500)),
                ('DoctorAddress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientFirstName', models.CharField(max_length=500)),
                ('PatientLastName', models.CharField(max_length=500)),
                ('PatientEmail', models.CharField(max_length=500)),
                ('PatientAddress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('RdvId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorId', models.IntegerField()),
                ('PatientId', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
