# Generated by Django 4.1.3 on 2022-12-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='DoctorId',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='PatientId',
        ),
    ]
