# Generated by Django 4.1.3 on 2022-12-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0002_remove_rdv_doctorid_remove_rdv_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='DoctorId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rdv',
            name='PatientId',
            field=models.IntegerField(default=-1),
        ),
    ]
