# Generated by Django 4.1.4 on 2023-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0007_alter_rdv_rdvdoctor_alter_rdv_rdvpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='EndTime',
            field=models.CharField(default='17:00', max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Interval',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='StartTime',
            field=models.CharField(default='09:00', max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='WorkDays',
            field=models.CharField(default='Sun,Mon,Tue,Wed,Thu', max_length=500),
        ),
    ]
