# Generated by Django 4.1.4 on 2023-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0008_doctor_endtime_doctor_interval_doctor_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DoctorPassword',
            field=models.CharField(default='doctor1', max_length=500),
        ),
    ]
