# Generated by Django 4.1.4 on 2023-01-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0009_doctor_doctorpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Latitude',
            field=models.FloatField(default=36.711823),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Longitude',
            field=models.FloatField(default=4.051717),
        ),
    ]
